import 'dataModel.dart';

Map photoSlider = {
  "slider-1": "assets/img/homeSlider/slider.webp",
  "slider-2":
      "https://www.mbusa.com/content/dam/mb-nafta/ca/myco/my23/eqb-suv/gallery/series/gallery-class/2023-EQB-SUV-GAL-004-XL.jpg"
};

List<CarsModel> carsList = [
  CarsModel(
    nameCarFA: "اس ال",
    nameCarEN: "AMG-SL",
    classCar: "کوپه",
    imgCar: "assets/img/AMG-SL/silver.webp",
    imgCarPNG: "assets/img/AMG-SL/silver.png",
    btnRedmore: 'مشاهده',
    speed: "350",
    power: "469 اسب بخار",
    cityFuelEconomy: "14 mpg",
    highwayFuelEconomy: "21 mpg",
    acceleration: "3.8 ثانیه",
    carVideo:
        "https://www.mbusa.com/content/dam/mb-nafta/us/myco/my22/sl/class-page/amg/2022-SL-ROADSTER-CT-4-2-DR.mp4",
    passengerCapacity: "4 نفره",
    engin: "3982",
    options: "",
    articleCar: "",
  ),
  CarsModel(
    nameCarFA: "جی کلاس",
    nameCarEN: "G-class",
    classCar: "شاسی بلند",
    imgCar: "assets/img/G-class/2022-G550-SUV-AVP-DR.webp",
    imgCarPNG: "assets/img/G-class/2022-G550-SUV-AVP-DR.png",
    btnRedmore: "مشاهده",
    speed: "240",
    power: "416 hp",
    cityFuelEconomy: "13 mpg",
    highwayFuelEconomy: "16 mpg",
    acceleration: "5.6 ثانیه",
    carVideo:
        "https://www.mbusa.com/content/dam/mb-nafta/us/myco/my23/g/class-page/series/2023-G-SUV-CT-2-2-DR.mp4",
    passengerCapacity: "5 نفره",
    engin: "2925",
    options: """این ماشین فول اپشن میباشد!""",
    articleCar: "",
  ),
  CarsModel(
    nameCarFA: "جی تی 43",
    nameCarEN: "AMG-GT",
    classCar: "کوپه",
    imgCar: "assets/img/AMG-GT/2022-AMG-GT43-4DR-COUPE-AVP-DR.webp",
    imgCarPNG: "assets/img/AMG-GT/2022-AMG-GT43-4DR-COUPE-AVP-DR.png",
    btnRedmore: "مشاهده",
    speed: "320",
    power: "362 اسب بخار",
    cityFuelEconomy: "19 mpg",
    highwayFuelEconomy: "25 mpg",
    acceleration: "3.2 ثانیه",
    carVideo:
        "https://www.mbusa.com/content/dam/mb-nafta/us/myco/my22/gt-4dr-coupe/class-page/2022-AMG-GT-4DR-COUPE-CT-3-2-DR.mp4",
    passengerCapacity: "",
    engin: "3982",
    options: "",
    articleCar: "",
  ),
  CarsModel(
    nameCarFA: "میباخ",
    nameCarEN: "MAYBACH",
    classCar: "واگن",
    imgCar: "assets/img/maybach/2022-MAYBACH-SEDAN-AVP-DR.webp",
    imgCarPNG: "assets/img/maybach/2022-MAYBACH-SEDAN-AVP-DR.png",
    btnRedmore: "مشاهده",
    speed: "320",
    power: "621 hp",
    cityFuelEconomy: "12 mpg",
    highwayFuelEconomy: "20 mpg",
    acceleration: "4.5 ثانیه",
    carVideo:
        "https://www.mbusa.com/content/dam/mb-nafta/us/myco/my23/s/maybach/class-page/series/S_maybach-page-hero-video.mp4",
    passengerCapacity: "5 نفره",
    engin: "3982",
    options: """این ماشین فول اپشن میباشد!""",
    articleCar: "",
  ),
  CarsModel(
    nameCarFA: "سی ال اس",
    nameCarEN: "CLS",
    classCar: "کوپه",
    imgCar: "assets/img/CLS/2022-CLS-COUPE-AVP-DR.webp",
    imgCarPNG: "assets/img/CLS/2022-CLS-COUPE-AVP-DR.png",
    btnRedmore: "مشاهده",
    speed: "320",
    power: "362 hp",
    cityFuelEconomy: "22 mpg",
    highwayFuelEconomy: "30 mpg",
    acceleration: "4.5 ثانیه",
    carVideo:
        "https://www.mercedes-amg.com/en/vehicles/cls/coupe/_jcr_content/stage/media/slides/slide_copy_copy/media1/video.video.20210406160320.mp4",
    passengerCapacity: "",
    engin: "3.0 لیتری 6 توربو خطی با محرک هیبریدی ملایم",
    options: """""",
    articleCar: "",
  ),
  CarsModel(
    nameCarFA: "جی ال اس",
    nameCarEN: "GLS",
    classCar: "شاسی بلند",
    imgCar: "",
    imgCarPNG: "assets/img/GLS/2022-GLS450-SUV-AVP-DR.png",
    btnRedmore: 'more',
    speed: "320",
    power: "362 hp",
    cityFuelEconomy: "18 mpg",
    highwayFuelEconomy: "23 mpg",
    acceleration: "5.9 ثانیه",
    carVideo:
        "https://www.mbusa.com/content/dam/mb-nafta/us/myco/my23/gls/suv/class-page/series/2023-GLS-SUV-CT-3-6-DR.mp4",
    passengerCapacity: "7 نفره",
    engin: " 3 سیلندر توربو",
    options: """""",
    articleCar: "",
  ),
  CarsModel(
    nameCarFA: "سی کلاس",
    nameCarEN: "C-class",
    classCar: "کوپه",
    imgCar: "",
    imgCarPNG: "assets/img/C-class/2022-C300-CABRIOLET-AVP-DR.png",
    btnRedmore: "more",
    speed: "320",
    power: "255 hp",
    cityFuelEconomy: "21 mpg",
    highwayFuelEconomy: "30 mpg",
    acceleration: "6.2 ثانیه",
    carVideo:
        "https://www.mbusa.com/content/dam/mb-nafta/us/myco/my22/c/cab/class-page/series/2021-C-CABRIOLET-CT-3-2-DR.mp4",
    passengerCapacity: "4 نفره",
    engin: "2 سیلند",
    options: """""",
    articleCar: "",
  ),
  CarsModel(
    nameCarFA: "اس کلاس",
    nameCarEN: "S-class",
    classCar: "واگن",
    imgCar: "",
    imgCarPNG: "assets/img/S-class/2022-S500-SEDAN-AVP-DR.png",
    btnRedmore: "more",
    speed: "320",
    power: "362 hp",
    cityFuelEconomy: "20 mpg",
    highwayFuelEconomy: "29 mpg ",
    acceleration: "4.4 ثانیه",
    carVideo: "",
    passengerCapacity: "5 نفره",
    engin: "3 لیتری",
    options: """""",
    articleCar: "",
  ),
  CarsModel(
    nameCarFA: "ای کیو ای",
    nameCarEN: "EQE-Sedan",
    classCar: "برقی",
    imgCar: "",
    imgCarPNG: "assets/img/EQE-Sedan/2023-EQE350-SEDAN-AVP-DR.png",
    btnRedmore: "more",
    speed: "320",
    power: "329 hp",
    cityFuelEconomy: "",
    highwayFuelEconomy: "",
    acceleration: "5.9 ثانیه",
    carVideo: "",
    passengerCapacity: "5 نفره",
    engin: "",
    options: """""",
    articleCar: "",
  ),
  CarsModel(
    nameCarFA: "جی ال سی",
    nameCarEN: "GLC-SUV",
    classCar: "SUV",
    imgCar: "",
    imgCarPNG: "assets/img/GLS/2022-GLS450-SUV-AVP-DR.png",
    btnRedmore: "more",
    speed: "320",
    power: "255 hp",
    cityFuelEconomy: "25 mpg",
    highwayFuelEconomy: "32 mpg",
    acceleration: "6.2 ثانیه",
    carVideo: "",
    passengerCapacity: "5 نفره",
    engin: "2 سیلندر توربو",
    options: """""",
    articleCar: "",
  ),
  CarsModel(
    nameCarFA: "میباخ",
    nameCarEN: "Mercedes-Maybach",
    classCar: "شاسی بلند",
    imgCar: "",
    imgCarPNG: "assets/img/Mercedes-Maybach/2021-MAYBACH-GLS-SUV-AVP-DR.png",
    btnRedmore: "more",
    speed: "340",
    power: "550 hp",
    cityFuelEconomy: "15 mpg",
    highwayFuelEconomy: "19 mpg Disclaimer",
    acceleration: "4.8 ثانیه",
    carVideo:
        "https://www.mbusa.com/content/dam/mb-nafta/us/myco/my22/gls/maybach/class-page/series/maybach-innovation-hero-video.mp4",
    passengerCapacity: "4 نفره",
    engin: "چهار لیتری - هشت توربو",
    options: """""",
    articleCar: "",
  ),
  CarsModel(
    nameCarFA: "ای کلاس",
    nameCarEN: "E-class",
    classCar: "sedan",
    imgCar: "",
    imgCarPNG: "assets/img/E-class/2022-E350-SEDAN-AVP-DR.png",
    btnRedmore: "more",
    speed: "320",
    power: "255 hp",
    cityFuelEconomy: "23 mpg",
    highwayFuelEconomy: "31 mpg",
    acceleration: "6.1 ثانیه",
    carVideo:
        "https://www.mbusa.com/content/dam/mb-nafta/us/myco/my22/e/sedan/class-page/series/2022-E-SEDAN-CT-2-2-DR.mp4",
    passengerCapacity: "5 نفره",
    engin: "دو سیلندر و چهار توربو",
    options: """""",
    articleCar: "",
  ),
  CarsModel(
    nameCarFA: "جی ال ای",
    nameCarEN: "GLE",
    classCar: "کوپه",
    imgCar: "",
    imgCarPNG: "assets/img/GLE/2022-AMG-GLE53-COUPE-AVP-DR.png",
    btnRedmore: "مشاهده",
    speed: "340",
    power: "",
    cityFuelEconomy: "",
    highwayFuelEconomy: "",
    acceleration: "",
    carVideo: "",
    passengerCapacity: "",
    engin: "",
    options: """""",
    articleCar: "",
  ),
  CarsModel(
    nameCarFA: "اِی کلاس",
    nameCarEN: "A-class",
    classCar: "sedan",
    imgCar: "",
    imgCarPNG: "assets/img/A-class/2022-A220-SEDAN-AVP-DR.png",
    btnRedmore: "more",
    speed: "340",
    power: "188 hp",
    cityFuelEconomy: "24 mpg",
    highwayFuelEconomy: "35 mpg",
    acceleration: "7.1 ثانیه",
    carVideo:
        "https://www.mbusa.com/content/dam/mb-nafta/us/myco/my22/a/class-page/series/2022-A-SEDAN-CT-1-5-DR.mp4",
    passengerCapacity: "5 نفره",
    engin: "دو سیلندر و چهار توربو",
    options: """""",
    articleCar: "",
  ),
  CarsModel(
    nameCarFA: "ای کیو اس",
    nameCarEN: "EQS-Sedan",
    classCar: "sedan",
    imgCar: "",
    imgCarPNG: "assets/img/EQS/2023-EQS450-SUV-AVP-DR.png",
    btnRedmore: "more",
    speed: "340",
    power: "355 hp",
    cityFuelEconomy: "24 mpg",
    highwayFuelEconomy: "35 mpg",
    acceleration: "6.5 ثانیه",
    carVideo:
        "https://www.mbusa.com/content/dam/mb-nafta/us/myco/my22/a/class-page/series/2022-A-SEDAN-CT-1-5-DR.mp4",
    passengerCapacity: "5 نفره",
    engin: "برقی",
    options: """""",
    articleCar: "",
  ),
];
